sudo: false
language: node_js
node_js:
  - 14
cache: npm
branches:
  only:
    - master # build master branch only

before_install:
  - export TZ='Asia/Shanghai'   # 配置时区为东八区 UTC+8
  - npm install hexo-cli        # 安装 hexo

# 执行脚本 
script:                         
  - hexo clean                  # 清除 hexo 缓存
  - hexo generate               # 生成静态文件

deploy:
  strategy: git
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN
  keep-history: true
  on:
    branch: master
  local-dir: public
  target_branch: gh-pages